import { useEffect, useState } from "react";
import { SPRITE_BASE_PATH } from "../../../core/domain/sprites";

/** Fetched once per page load and shared — several fields can offer the sprite list without refetching it each. */
let cache: string[] | null = null;
let inFlight: Promise<string[]> | null = null;

function loadManifest(): Promise<string[]> {
    if (cache) return Promise.resolve(cache);
    inFlight ??= fetch(`${SPRITE_BASE_PATH}manifest.json`)
        .then((response) => {
            if (!response.ok) throw new Error(`HTTP ${response.status}`);
            return response.json() as Promise<string[]>;
        })
        .then((files) => {
            cache = files;
            return files;
        })
        .catch(() => {
            // A missing manifest just means "no list to offer" — the field stays a plain text input.
            cache = [];
            return cache;
        });
    return inFlight;
}

/**
 * Filenames of the item sprites the site actually ships (`public/roulette_interface/pod-mini-characters`,
 * generated by scripts/generate-sprite-manifest.mjs). This is the only sprite set that reaches the deployed
 * site — CI syncs this folder plus the tag icons, and nothing else — so it's the whole universe of pickable
 * sprites. House sprites ("mini houses") exist only on a local sync and are deliberately not offered.
 */
export function useSpriteManifest(): string[] {
    const [files, setFiles] = useState<string[]>(cache ?? []);

    useEffect(() => {
        let cancelled = false;
        void loadManifest().then((loaded) => {
            if (!cancelled) setFiles(loaded);
        });
        return () => {
            cancelled = true;
        };
    }, []);

    return files;
}
